### ISSUE TITLE
Person uses ArrayList in signatures instead of List

### ISSUE THREAD

**Issue by peshitz** [piplcom/piplapis-java#4]
Person uses ArrayList in signatures instead of List: no need to be specific about the implementation as this is less convenient for caller. For example, caller can't use Arrays.asList(...) since it doesn't produce an java.util.ArrayList

**Comment by pipldev** [comment]
As far as I can see ArrayList is only used on a return value. This gives more information to the caller (get() will be o(1)), without imposing any limitation on the caller. The caller is free to assign the ArrayList to a List if he/she wants. 
This is not something that can be changed, as it will break backwards-compatibility.
