### ISSUE TITLE
NullPointerException deserializing DateRange with start == null

### ISSUE THREAD

**Issue by AlbertoHocelot** [piplcom/piplapis-java#7]
The method com.pipl.api.data.fields.DateRange#isExact throws a NullPointerException while deserialization when start is null.

This is due to the method signature follows the getter conversion so the serialization library (e.g. Jackson) tries to deserialize the field.

- Solution 1:
mark the method as not serializable (e.g. add @Transient to the method)

- Soluction 2:
The method code:
`public boolean isExact() {
	return start.equals(end);
}`
Should be replaced with
`public boolean isExact() {
	return start != null && start.equals(end);
}`.

It could be a great idea to review the rest of the SDK to avoid NullPointerExeption.

**Comment by yuri1992** [comment]
Solved by https://github.com/piplcom/piplapis-java/pull/13
Released under 5.0.14
